[styleTitle]
StringAlign=Left
StringStyle=BOLD
StringEffect=SHADOW
FontEffectColor=0,0,0,50
FontFace=#fontName#
FontSize=#textSizeTitle#
FontColor=#colorTitle#
AntiAlias=1
ClipString=1

[styleDataLeft]
StringAlign=LEFT
StringStyle=BOLD
StringCase=NONE
FontFace=#fontName#
FontSize=#textSizeData#
FontColor=#colorText#
AntiAlias=1
ClipString=1

[styleDataLeftSmall]
StringAlign=LEFT
StringStyle=BOLD
StringCase=NONE
FontFace=#fontName#
FontSize=#textSizeDataSmall#
FontColor=#colorText#
AntiAlias=1
ClipString=1

[styleDataRight]
StringAlign=RIGHT
StringStyle=BOLD
StringCase=NONE
FontFace=#fontName#
FontSize=#textSizeData#
FontColor=#colorText#
AntiAlias=1
ClipString=1

[styleDataRightSmall]
StringAlign=RIGHT
StringStyle=BOLD
StringCase=NONE
FontFace=#fontName#
FontSize=#textSizeDataSmall#
FontColor=#colorText#
AntiAlias=1
ClipString=1

[styleSeperator]
LineColor=0,0,0,100
LineWidth=1

[styleInnerSeperator]
LineColor=255,255,255,60
LineWidth=1

[StyleBar]
BarOrientation=Horizontal
DynamicVariables=1